# 개발자 PC에서 실행할 때 사용
# H2 데이터베이스 사용 (설치 불필요, 메모리에서 실행)

spring:
    # H2 데이터베이스 설정
    datasource:
        url: jdbc:h2:mem:ecommerce
        # jdbc:h2:mem:ecommerce 의미:
        # - jdbc: 자바에서 DB 접속하는 표준 방식
        # - h2: H2 데이터베이스 사용
        # - mem: 메모리에 저장 (서버 끄면 데이터 사라짐)
        # - ecommerce: 데이터베이스 이름

        driver-class-name: org.h2.Driver # H2 드라이버
        username: sa # 기본 사용자 (System Administrator)
        password: # 비밀번호 없음 (로컬이라 보안 불필요)

    # H2 콘솔 활성화 (브라우저에서 DB 확인 가능)
    h2:
        console:
            enabled: true # http://localhost:8080/h2-console 접속 가능
            path: /h2-console

    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: create-drop
            # create-drop 의미:
            # - 서버 시작할 때: 테이블 자동 생성
            # - 서버 종료할 때: 테이블 자동 삭제
            # ⚠️ 개발할 때만 사용! 운영에서는 절대 안 됨!

        show-sql: true # SQL 쿼리를 콘솔에 출력 (디버깅용)
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect # H2 문법 사용

# Spring Security 임시 비활성화 (개발 편의성)
# 나중에 인증 기능 구현할 때 활성화
spring.security.user:
    name: admin # 기본 사용자
    password: admin # 기본 비밀번호

# 로깅 레벨
logging:
    level:
        org.hibernate.SQL: DEBUG # SQL 쿼리 출력
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 출력
        # BasicBinder를 TRACE로 설정하면:
        # SQL: SELECT * FROM users WHERE id = ?
        # 파라미터: [1] 이렇게 물음표에 들어간 값을 볼 수 있음
